### ISSUE TITLE
Predictions display is still incorrect

### ISSUE THREAD

**Issue by mathcolo** [nettube/mbtapuller#61] opened 2016-08-07 16:04 UTC
I wasn't on target yesterday as much as I thought. Predictions are still wrong, working on it

**Comment by mathcolo** [comment] 2016-08-09 01:23
Yeah, uh...we just forgot to merge the branch in ✌️

**Comment by tinzerillo** [comment] 2016-08-09 01:24
Hm?

**Comment by mathcolo** [comment] 2016-08-09 01:27
What I did over the weekend was correct, I just never PRed so I thought master had the changes in!

**Comment by tinzerillo** [comment] 2016-08-09 01:29
😂😂😂

**Comment by tinzerillo** [comment] 2016-08-09 03:28
DUPLICATE OF ISSUE #36

**Closed as completed by tinzerillo** 2016-08-09 03:28 UTC
Labels: bug
